"""
dashboard.py — PlaySight AI Analytics Dashboard
================================================
Beautiful visualization dashboard for player improvement and coach analysis.
Reads the 3 CSV files generated by main.py.

Usage:
    pip install streamlit plotly pandas numpy
    streamlit run dashboard.py

Then open http://localhost:8501 in your browser.
Point the sidebar to your csv_output/ folder.
"""

import os
import glob
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import streamlit as st

# ─────────────────────────────────────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="PlaySight AI — Coach Dashboard",
    page_icon="🏸",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────────────────────────────────────
# THEME — dark sport aesthetic
# ─────────────────────────────────────────────────────────────────────────────
THEME = dict(
    bg        = "#070810",
    surface   = "#0d0f1c",
    surface2  = "#131629",
    border    = "#1e2240",
    blue      = "#4f8bff",
    green     = "#00e57a",
    yellow    = "#ffd54f",
    red       = "#ff5252",
    purple    = "#b388ff",
    cyan      = "#40e0ff",
    orange    = "#ff8c42",
    text      = "#e8ecff",
    muted     = "#5a6080",
)

SHOT_COLORS = {
    "SMASH":   "#ff5252",
    "CLEAR":   "#ffd54f",
    "DRIVE":   "#ff8c42",
    "DROP":    "#40e0ff",
    "NETSHOT": "#00e57a",
    "LIFT":    "#b388ff",
}
QUALITY_COLORS = {
    "GOOD":    "#00e57a",
    "AVERAGE": "#ffd54f",
    "BAD":     "#ff5252",
}

PLOTLY_THEME = dict(
    paper_bgcolor = THEME["surface"],
    plot_bgcolor  = THEME["surface"],
    font          = dict(color=THEME["text"], family="monospace"),
    margin        = dict(l=20, r=20, t=40, b=20),
)

# Default axis style — applied manually where needed
AXIS_STYLE = dict(gridcolor=THEME["border"], zerolinecolor=THEME["border"])

st.markdown(f"""
<style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Syne:wght@700;800&display=swap');

    html, body, [class*="css"] {{
        background-color: {THEME['bg']};
        color: {THEME['text']};
        font-family: 'JetBrains Mono', monospace;
    }}
    .main {{ background-color: {THEME['bg']}; }}
    .block-container {{ padding: 2rem 2rem 4rem; max-width: 1600px; }}

    h1 {{ font-family: 'Syne', sans-serif; font-weight: 800;
          background: linear-gradient(135deg, #fff, {THEME['blue']});
          -webkit-background-clip: text; -webkit-text-fill-color: transparent; }}
    h2, h3 {{ font-family: 'Syne', sans-serif; color: {THEME['text']}; }}

    .metric-card {{
        background: {THEME['surface']};
        border: 1px solid {THEME['border']};
        border-radius: 12px;
        padding: 20px;
        text-align: center;
    }}
    .metric-value {{
        font-size: 2.2rem;
        font-weight: 800;
        font-family: 'Syne', sans-serif;
    }}
    .metric-label {{
        font-size: 0.7rem;
        letter-spacing: 0.15em;
        text-transform: uppercase;
        color: {THEME['muted']};
        margin-top: 4px;
    }}
    .insight-card {{
        background: {THEME['surface']};
        border-left: 3px solid {THEME['blue']};
        border-radius: 0 12px 12px 0;
        padding: 16px 20px;
        margin: 8px 0;
    }}
    .insight-card.good  {{ border-color: {THEME['green']}; }}
    .insight-card.warn  {{ border-color: {THEME['yellow']}; }}
    .insight-card.bad   {{ border-color: {THEME['red']}; }}
    .stSelectbox label, .stSlider label {{ color: {THEME['muted']} !important; }}
    .stSidebar {{ background: {THEME['surface']}; }}

    /* section headers */
    .section-header {{
        font-family: 'JetBrains Mono', monospace;
        font-size: 0.65rem;
        letter-spacing: 0.25em;
        text-transform: uppercase;
        color: {THEME['muted']};
        border-bottom: 1px solid {THEME['border']};
        padding-bottom: 8px;
        margin: 32px 0 16px;
    }}
    div[data-testid="stMetric"] {{
        background: {THEME['surface']};
        border: 1px solid {THEME['border']};
        border-radius: 12px;
        padding: 16px;
    }}
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# SIDEBAR — file picker
# ─────────────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🏸 PlaySight AI")
    st.markdown("---")
    st.markdown("### Load CSV Files")

    csv_dir = st.text_input(
        "CSV folder path",
        value="csv_output",
        help="Path to the folder containing the 3 CSV files from main.py"
    )

    # Auto-detect latest files in the directory
    def find_csv(folder, pattern):
        files = glob.glob(os.path.join(folder, f"{pattern}*.csv"))
        return sorted(files)[-1] if files else None

    bio_file  = find_csv(csv_dir, "player_biomechanics")
    shot_file = find_csv(csv_dir, "shot_events")
    court_file= find_csv(csv_dir, "court_keypoints")

    if bio_file:
        st.success(f"✅ {os.path.basename(bio_file)}")
    else:
        st.error("❌ player_biomechanics not found")

    if shot_file:
        st.success(f"✅ {os.path.basename(shot_file)}")
    else:
        st.error("❌ shot_events not found")

    if court_file:
        st.success(f"✅ {os.path.basename(court_file)}")
    else:
        st.warning("⚠ court_keypoints not found")

    st.markdown("---")
    selected_player = st.selectbox(
        "Focus Player", ["All Players", "Player 1", "Player 2"])

    st.markdown("---")
    st.markdown(
        "<div style='color:#5a6080;font-size:11px'>"
        "PlaySight AI Dashboard<br>Coach Analysis Tool"
        "</div>", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────────────────────────────────────
@st.cache_data
def load_data(bio_path, shot_path, court_path):
    bio   = pd.read_csv(bio_path)   if bio_path   else pd.DataFrame()
    shots = pd.read_csv(shot_path)  if shot_path  else pd.DataFrame()
    court = pd.read_csv(court_path) if court_path else pd.DataFrame()
    return bio, shots, court

if not bio_file or not shot_file:
    st.title("🏸 PlaySight AI — Coach Dashboard")
    st.markdown("""
    **No CSV files found.**

    Run the analysis first:
    ```bash
    python main.py
    ```
    Then set the CSV folder path in the sidebar.
    """)
    st.stop()

bio, shots, court = load_data(bio_file, shot_file, court_file)

# Filter by player if selected
if selected_player == "Player 1":
    bio   = bio[bio["player_id"] == 1]
    shots = shots[shots["player_id"] == 1]
elif selected_player == "Player 2":
    bio   = bio[bio["player_id"] == 2]
    shots = shots[shots["player_id"] == 2]

if shots.empty:
    st.warning("No shot events found. Check your CSV files.")
    st.stop()

players = shots["player_id"].unique()


# ─────────────────────────────────────────────────────────────────────────────
# HEADER
# ─────────────────────────────────────────────────────────────────────────────
st.title("🏸 PlaySight AI — Coach Dashboard")
st.markdown(
    f"<div style='color:{THEME['muted']};font-size:12px;margin-top:-12px;margin-bottom:24px'>"
    f"Analysing: <b style='color:{THEME['blue']}'>{os.path.basename(shot_file)}</b> — "
    f"{len(shots)} shot events · {selected_player}"
    "</div>", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# ① KPI METRICS ROW
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Match Overview</div>", unsafe_allow_html=True)

total_shots   = len(shots)
good_pct      = round(100 * (shots["quality"] == "GOOD").sum()   / total_shots, 1)
avg_pct       = round(100 * (shots["quality"] == "AVERAGE").sum()/ total_shots, 1)
bad_pct       = round(100 * (shots["quality"] == "BAD").sum()    / total_shots, 1)
avg_speed     = round(shots["shuttle_speed_kmh"].mean(), 1)
avg_react     = round(shots["reaction_time_s"].mean(), 2)
avg_recovery  = round(shots["recovery_score"].mean(), 3)
dominant_shot = shots["shot_type"].value_counts().idxmax()

c1,c2,c3,c4,c5,c6,c7 = st.columns(7)
c1.metric("Total Shots",    total_shots)
c2.metric("🟢 GOOD",        f"{good_pct}%",  delta=f"+{good_pct-avg_pct:.1f}% vs avg")
c3.metric("🟡 AVERAGE",     f"{avg_pct}%")
c4.metric("🔴 BAD",         f"{bad_pct}%",   delta=f"-{bad_pct:.1f}%", delta_color="inverse")
c5.metric("Avg Speed",      f"{avg_speed} km/h")
c6.metric("Avg React Time", f"{avg_react}s")
c7.metric("Dominant Shot",  dominant_shot)


# ─────────────────────────────────────────────────────────────────────────────
# ② SHOT DISTRIBUTION + QUALITY BREAKDOWN
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Shot Analysis</div>", unsafe_allow_html=True)

col1, col2 = st.columns([1, 1])

with col1:
    st.markdown("#### Shot Type Distribution")
    shot_counts = shots["shot_type"].value_counts().reset_index()
    shot_counts.columns = ["shot_type", "count"]
    shot_counts["color"] = shot_counts["shot_type"].map(SHOT_COLORS)

    fig_donut = go.Figure(go.Pie(
        labels    = shot_counts["shot_type"],
        values    = shot_counts["count"],
        hole      = 0.55,
        marker    = dict(colors=shot_counts["color"].tolist(),
                        line=dict(color=THEME["surface"], width=3)),
        textinfo  = "label+percent",
        textfont  = dict(size=12, color=THEME["text"]),
        hovertemplate = "<b>%{label}</b><br>%{value} shots (%{percent})<extra></extra>",
    ))
    fig_donut.add_annotation(
        text=f"<b>{total_shots}</b><br><span style='font-size:10px'>shots</span>",
        x=0.5, y=0.5, showarrow=False,
        font=dict(size=18, color=THEME["text"]))
    fig_donut.update_layout(**PLOTLY_THEME, showlegend=False, height=320)
    st.plotly_chart(fig_donut, use_container_width=True)

with col2:
    st.markdown("#### Quality Per Shot Type")
    quality_order = ["GOOD", "AVERAGE", "BAD"]
    shot_quality = shots.groupby(["shot_type", "quality"]).size().unstack(
        fill_value=0).reindex(columns=quality_order, fill_value=0)
    shot_quality_pct = shot_quality.div(shot_quality.sum(axis=1), axis=0) * 100

    fig_bar = go.Figure()
    for q, col in zip(quality_order, [THEME["green"], THEME["yellow"], THEME["red"]]):
        vals = shot_quality_pct[q] if q in shot_quality_pct.columns else [0]*len(shot_quality_pct)
        fig_bar.add_trace(go.Bar(
            name=q, x=shot_quality_pct.index,
            y=vals, marker_color=col,
            hovertemplate=f"<b>%{{x}}</b><br>{q}: %{{y:.1f}}%<extra></extra>",
        ))
    fig_bar.update_layout(
        **PLOTLY_THEME, barmode="stack", height=320,
        legend=dict(orientation="h", y=1.08, x=0.5, xanchor="center",
                    font=dict(color=THEME["text"], size=11)),
        xaxis=dict(title="Shot Type", gridcolor=THEME["border"]),
        yaxis=dict(title="Quality %", range=[0,100], gridcolor=THEME["border"]),
    )
    st.plotly_chart(fig_bar, use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# ③ SHUTTLE SPEED ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Shuttle Speed Analysis</div>", unsafe_allow_html=True)

col1, col2 = st.columns([1.3, 1])

with col1:
    st.markdown("#### Speed Over Match Timeline")
    shots_sorted = shots.sort_values("frame")

    fig_speed = go.Figure()
    for pid in players:
        df_p = shots_sorted[shots_sorted["player_id"] == pid]
        fig_speed.add_trace(go.Scatter(
            x=df_p["frame"], y=df_p["shuttle_speed_kmh"],
            mode="markers+lines",
            name=f"P{pid}",
            marker=dict(
                size=8,
                color=[QUALITY_COLORS.get(q, THEME["muted"])
                       for q in df_p["quality"]],
                line=dict(color=THEME["surface"], width=1),
            ),
            line=dict(color=THEME["blue"] if pid==1 else THEME["orange"],
                      width=1, dash="dot"),
            hovertemplate=(
                "<b>P%{customdata[0]}</b><br>"
                "Frame: %{x}<br>Speed: %{y:.0f} km/h<br>"
                "Shot: %{customdata[1]} [%{customdata[2]}]<extra></extra>"
            ),
            customdata=list(zip(df_p["player_id"],
                               df_p["shot_type"],
                               df_p["quality"])),
        ))
    # Add moving average
    if len(shots_sorted) > 5:
        ma = shots_sorted["shuttle_speed_kmh"].rolling(5, min_periods=1).mean()
        fig_speed.add_trace(go.Scatter(
            x=shots_sorted["frame"], y=ma,
            mode="lines", name="5-shot avg",
            line=dict(color=THEME["cyan"], width=2),
            hoverinfo="skip",
        ))
    fig_speed.update_layout(
        **PLOTLY_THEME, height=320,
        xaxis=dict(title="Frame", gridcolor=THEME["border"]),
        yaxis=dict(title="Speed (km/h)", gridcolor=THEME["border"]),
        legend=dict(font=dict(color=THEME["text"], size=10)),
    )
    st.plotly_chart(fig_speed, use_container_width=True)

with col2:
    st.markdown("#### Speed by Shot Type (Box)")
    fig_box = go.Figure()
    for shot_type, color in SHOT_COLORS.items():
        df_s = shots[shots["shot_type"] == shot_type]
        if df_s.empty: continue
        fig_box.add_trace(go.Box(
            y=df_s["shuttle_speed_kmh"],
            name=shot_type,
            marker_color=color,
            line_color=color,
            boxmean=True,
            hovertemplate=(
                f"<b>{shot_type}</b><br>"
                "Speed: %{y:.0f} km/h<extra></extra>"
            ),
        ))
    fig_box.update_layout(
        **PLOTLY_THEME, height=320,
        showlegend=False,
        yaxis=dict(title="Speed (km/h)", gridcolor=THEME["border"]),
    )
    st.plotly_chart(fig_box, use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# ④ BIOMECHANICS — JOINT ANGLES OVER TIME
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Biomechanics — Joint Analysis</div>",
            unsafe_allow_html=True)

JOINT_PAIRS = {
    "Elbow (R/L)":     ("right_elbow_angle",    "left_elbow_angle"),
    "Shoulder (R/L)":  ("right_shoulder_angle",  "left_shoulder_angle"),
    "Knee (R/L)":      ("right_knee_angle",      "left_knee_angle"),
    "Wrist (R/L)":     ("right_wrist_angle",     "left_wrist_angle"),
    "Hip (R/L)":       ("right_hip_angle",       "left_hip_angle"),
    "Ankle (R/L)":     ("right_ankle_angle",     "left_ankle_angle"),
}

col1, col2 = st.columns([2, 1])

with col1:
    joint_sel = st.selectbox("Select Joint", list(JOINT_PAIRS.keys()))
    r_col, l_col = JOINT_PAIRS[joint_sel]

    # Sample bio data for performance (max 2000 rows)
    bio_sample = bio.sample(min(2000, len(bio))).sort_values("frame") \
                 if len(bio) > 2000 else bio.sort_values("frame")

    fig_joint = go.Figure()
    for pid in bio_sample["player_id"].unique():
        df_p = bio_sample[bio_sample["player_id"] == pid]
        c_r  = THEME["blue"]   if pid == 1 else THEME["orange"]
        c_l  = THEME["purple"] if pid == 1 else THEME["cyan"]

        fig_joint.add_trace(go.Scatter(
            x=df_p["frame"],
            y=df_p[r_col] * 180,   # convert back to degrees for readability
            mode="lines", name=f"P{pid} Right",
            line=dict(color=c_r, width=1.5),
            opacity=0.85,
        ))
        fig_joint.add_trace(go.Scatter(
            x=df_p["frame"],
            y=df_p[l_col] * 180,
            mode="lines", name=f"P{pid} Left",
            line=dict(color=c_l, width=1.5, dash="dot"),
            opacity=0.85,
        ))

    # Overlay shot events as vertical lines
    for _, row in shots.iterrows():
        color = SHOT_COLORS.get(row["shot_type"], THEME["muted"])
        fig_joint.add_vline(
            x=row["frame"], line_width=1,
            line_color=color, opacity=0.3,
        )

    fig_joint.update_layout(
        **PLOTLY_THEME, height=350,
        xaxis=dict(title="Frame", gridcolor=THEME["border"]),
        yaxis=dict(title=f"{joint_sel} angle (°)", range=[0,180], gridcolor=THEME["border"]),
        legend=dict(font=dict(color=THEME["text"], size=10),
                   orientation="h", y=1.08),
        title=dict(text=f"{joint_sel} — coloured lines = shot events",
                  font=dict(size=11, color=THEME["muted"])),
    )
    st.plotly_chart(fig_joint, use_container_width=True)

with col2:
    st.markdown("#### Avg Joint Angles by Shot Type")
    angle_cols = [c for c in bio.columns if "_angle" in c]
    joint_by_shot = shots.groupby("shot_type")[
        [c for c in angle_cols if c in shots.columns]
    ].mean() * 180

    if not joint_by_shot.empty:
        fig_heat = go.Figure(go.Heatmap(
            z=joint_by_shot.values,
            x=[c.replace("_angle","").replace("_"," ").title()
               for c in joint_by_shot.columns],
            y=joint_by_shot.index,
            colorscale=[[0,"#070810"],[0.5,"#4f8bff"],[1,"#00e57a"]],
            hovertemplate="Shot: %{y}<br>Joint: %{x}<br>Avg: %{z:.1f}°<extra></extra>",
            text=joint_by_shot.values.round(0),
            texttemplate="%{text}°",
            textfont=dict(size=9, color=THEME["text"]),
        ))
        fig_heat.update_layout(
            **PLOTLY_THEME, height=350,
            xaxis=dict(tickangle=-30, tickfont=dict(size=9), gridcolor=THEME["border"]),
            yaxis=dict(gridcolor=THEME["border"]),
        )
        st.plotly_chart(fig_heat, use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# ⑤ POSTURE & DYNAMICS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Posture & Movement Dynamics</div>",
            unsafe_allow_html=True)

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("#### Jump Events")
    jump_data = bio[bio["jump_flag"] == 1]
    fig_jump  = go.Figure()

    for pid in bio["player_id"].unique():
        df_j = bio[bio["player_id"] == pid]
        fig_jump.add_trace(go.Scatter(
            x=df_j["frame"], y=df_j["jump_height_norm"],
            mode="lines", fill="tozeroy",
            name=f"P{pid}",
            fillcolor=(f"rgba(79,139,255,0.15)" if pid==1
                       else "rgba(255,140,66,0.15)"),
            line=dict(color=THEME["blue"] if pid==1 else THEME["orange"],
                     width=1.5),
        ))

    jump_count = len(jump_data)
    fig_jump.add_annotation(
        text=f"{jump_count} jumps detected",
        x=0.5, y=0.95, xref="paper", yref="paper",
        showarrow=False,
        font=dict(color=THEME["green"], size=11),
    )
    fig_jump.update_layout(
        **PLOTLY_THEME, height=260,
        xaxis=dict(title="Frame", gridcolor=THEME["border"]),
        yaxis=dict(title="Jump Height (norm)", gridcolor=THEME["border"]),
        showlegend=True,
        legend=dict(font=dict(size=9, color=THEME["text"])),
    )
    st.plotly_chart(fig_jump, use_container_width=True)

with col2:
    st.markdown("#### Stance Width Over Time")
    fig_stance = go.Figure()
    for pid in bio["player_id"].unique():
        df_s = bio[bio["player_id"] == pid].sort_values("frame")
        # Rolling average
        rolled = df_s["stance_width_norm"].rolling(30, min_periods=1).mean()
        fig_stance.add_trace(go.Scatter(
            x=df_s["frame"], y=rolled,
            mode="lines", name=f"P{pid}",
            line=dict(color=THEME["cyan"] if pid==1 else THEME["purple"],
                     width=2),
        ))
    # Ideal range band
    fig_stance.add_hrect(y0=0.4, y1=0.7,
        fillcolor=f"rgba(0,229,122,0.08)",
        line_width=0, annotation_text="Ideal range",
        annotation_font_color=THEME["green"],
        annotation_font_size=9)
    fig_stance.update_layout(
        **PLOTLY_THEME, height=260,
        xaxis=dict(title="Frame", gridcolor=THEME["border"]),
        yaxis=dict(title="Stance Width (norm)", range=[0,1], gridcolor=THEME["border"]),
        legend=dict(font=dict(size=9, color=THEME["text"])),
    )
    st.plotly_chart(fig_stance, use_container_width=True)

with col3:
    st.markdown("#### Wrist Speed Distribution")
    fig_wr = go.Figure()
    for pid in bio["player_id"].unique():
        df_w = bio[bio["player_id"]==pid]["wrist_speed_norm"]
        fig_wr.add_trace(go.Violin(
            y=df_w, name=f"P{pid}",
            box_visible=True, meanline_visible=True,
            fillcolor=(f"rgba(79,139,255,0.3)" if pid==1
                      else "rgba(255,140,66,0.3)"),
            line_color=THEME["blue"] if pid==1 else THEME["orange"],
            opacity=0.8,
        ))
    fig_wr.update_layout(
        **PLOTLY_THEME, height=260,
        yaxis=dict(title="Wrist Speed (norm)", gridcolor=THEME["border"]),
        showlegend=True,
        legend=dict(font=dict(size=9, color=THEME["text"])),
    )
    st.plotly_chart(fig_wr, use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# ⑥ COURT POSITION HEATMAP
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Court Positioning</div>",
            unsafe_allow_html=True)

col1, col2 = st.columns(2)

for col_idx, pid in enumerate(players[:2]):
    df_p = bio[bio["player_id"] == pid]
    with (col1 if col_idx == 0 else col2):
        st.markdown(f"#### Player {pid} — Position Heatmap")
        fig_hm = go.Figure(go.Histogram2d(
            x=df_p["pos_x_norm"],
            y=1 - df_p["pos_y_norm"],   # invert so top of court = top
            nbinsx=20, nbinsy=20,
            colorscale=[
                [0,   THEME["surface"]],
                [0.3, "#1a2060"],
                [0.6, THEME["blue"]],
                [0.85,THEME["cyan"]],
                [1,   THEME["green"]],
            ],
            showscale=False,
            hovertemplate="x: %{x:.2f}<br>y: %{y:.2f}<br>count: %{z}<extra></extra>",
        ))
        # Court outline
        fig_hm.add_shape(type="rect", x0=0, y0=0, x1=1, y1=1,
            line=dict(color=THEME["muted"], width=1, dash="dot"))
        # Net
        fig_hm.add_hline(y=0.5, line_color=THEME["yellow"],
                          line_width=1.5, opacity=0.6,
                          annotation_text="NET", annotation_font_size=9,
                          annotation_font_color=THEME["yellow"])
        # Shot positions overlay
        df_ps = shots[shots["player_id"] == pid]
        if not df_ps.empty:
            fig_hm.add_trace(go.Scatter(
                x=df_ps["pos_x_norm"],
                y=1 - df_ps["pos_y_norm"],
                mode="markers",
                name="Shot events",
                marker=dict(
                    color=[SHOT_COLORS.get(s, THEME["muted"])
                           for s in df_ps["shot_type"]],
                    size=8, opacity=0.9,
                    line=dict(color=THEME["surface"], width=1),
                ),
                hovertemplate=(
                    "<b>%{customdata[0]}</b> [%{customdata[1]}]<extra></extra>"
                ),
                customdata=list(zip(df_ps["shot_type"], df_ps["quality"])),
            ))

        fig_hm.update_layout(
            **PLOTLY_THEME, height=380,
            xaxis=dict(range=[0,1], title="Court Width", showgrid=False),
            yaxis=dict(range=[0,1], title="Court Length", showgrid=False),
            showlegend=True,
            legend=dict(font=dict(size=9, color=THEME["text"])),
        )
        st.plotly_chart(fig_hm, use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# ⑦ REACTION TIME & RECOVERY ANALYSIS
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Timing & Recovery</div>",
            unsafe_allow_html=True)

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("#### Reaction Time by Shot Quality")
    fig_react = px.violin(
        shots, y="reaction_time_s", x="quality",
        color="quality",
        color_discrete_map=QUALITY_COLORS,
        box=True, points="outliers",
    )
    fig_react.update_layout(
        **PLOTLY_THEME, height=300,
        showlegend=False,
        xaxis=dict(title="Quality", gridcolor=THEME["border"]),
        yaxis=dict(title="Reaction Time (s)", gridcolor=THEME["border"]),
    )
    st.plotly_chart(fig_react, use_container_width=True)

with col2:
    st.markdown("#### Recovery Score by Shot Type")
    fig_rec = go.Figure()
    for shot_type, color in SHOT_COLORS.items():
        df_s = shots[shots["shot_type"] == shot_type]
        if df_s.empty: continue
        fig_rec.add_trace(go.Bar(
            x=[shot_type],
            y=[df_s["recovery_score"].mean()],
            name=shot_type,
            marker_color=color,
            hovertemplate=f"<b>{shot_type}</b><br>Avg Recovery: %{{y:.3f}}<extra></extra>",
        ))
    fig_rec.add_hline(y=0.5, line_dash="dash",
                      line_color=THEME["yellow"], opacity=0.5,
                      annotation_text="0.5 threshold",
                      annotation_font_size=9)
    fig_rec.update_layout(
        **PLOTLY_THEME, height=300,
        showlegend=False,
        xaxis=dict(title="Shot Type", gridcolor=THEME["border"]),
        yaxis=dict(title="Recovery Score (0-1)", range=[0,1], gridcolor=THEME["border"]),
    )
    st.plotly_chart(fig_rec, use_container_width=True)

with col3:
    st.markdown("#### Contact Height vs Quality")
    fig_ch = px.strip(
        shots, x="quality", y="contact_height_norm",
        color="quality",
        color_discrete_map=QUALITY_COLORS,
        stripmode="overlay",
    )
    fig_ch.update_traces(marker=dict(size=6, opacity=0.7))
    fig_ch.update_layout(
        **PLOTLY_THEME, height=300,
        showlegend=False,
        xaxis=dict(title="Quality", gridcolor=THEME["border"]),
        yaxis=dict(title="Contact Height (1=top)", range=[0,1], gridcolor=THEME["border"]),
    )
    st.plotly_chart(fig_ch, use_container_width=True)


# ─────────────────────────────────────────────────────────────────────────────
# ⑧ P1 vs P2 RADAR COMPARISON
# ─────────────────────────────────────────────────────────────────────────────
if len(players) >= 2:
    st.markdown("<div class='section-header'>Player Comparison — P1 vs P2</div>",
                unsafe_allow_html=True)

    col1, col2 = st.columns([1.2, 1])

    with col1:
        st.markdown("#### Skill Radar")
        RADAR_METRICS = {
            "Shot Quality":     lambda df: (df["quality_score"].mean()),
            "Speed":            lambda df: df["shuttle_speed_norm"].mean(),
            "Contact Height":   lambda df: df["contact_height_norm"].mean(),
            "Recovery":         lambda df: df["recovery_score"].mean(),
            "Elbow Extension":  lambda df: df["elbow_extension_norm"].mean() if "elbow_extension_norm" in df.columns else 0,
            "Reaction Speed":   lambda df: 1 - df["reaction_time_norm"].mean(),
            "Jump Activity":    lambda df: df["jump_at_contact"].mean(),
        }
        categories = list(RADAR_METRICS.keys())

        fig_radar = go.Figure()
        for pid, color in zip([1,2],[THEME["blue"], THEME["orange"]]):
            df_p = shots[shots["player_id"] == pid]
            if df_p.empty: continue
            vals = [round(fn(df_p), 3) for fn in RADAR_METRICS.values()]
            vals_closed = vals + [vals[0]]
            cats_closed = categories + [categories[0]]
            fig_radar.add_trace(go.Scatterpolar(
                r=vals_closed, theta=cats_closed,
                fill="toself", name=f"Player {pid}",
                line=dict(color=color, width=2),
                fillcolor=color.replace("#","rgba(").replace(
                    ")", ",0.1)") if "#" in color else f"rgba(79,139,255,0.1)",
                marker=dict(size=6),
            ))

        fig_radar.update_layout(
            **PLOTLY_THEME,
            height=400,
            polar=dict(
                bgcolor=THEME["surface"],
                radialaxis=dict(
                    visible=True, range=[0,1],
                    gridcolor=THEME["border"],
                    tickfont=dict(size=9, color=THEME["muted"]),
                    tickvals=[0.25,0.5,0.75,1.0],
                ),
                angularaxis=dict(
                    gridcolor=THEME["border"],
                    tickfont=dict(size=10, color=THEME["text"]),
                ),
            ),
            showlegend=True,
            legend=dict(font=dict(color=THEME["text"])),
        )
        st.plotly_chart(fig_radar, use_container_width=True)

    with col2:
        st.markdown("#### Head-to-Head Stats")
        rows = []
        for metric, fn in RADAR_METRICS.items():
            p1_val = fn(shots[shots["player_id"]==1]) if 1 in players else 0
            p2_val = fn(shots[shots["player_id"]==2]) if 2 in players else 0
            winner = "P1" if p1_val > p2_val else "P2"
            rows.append({
                "Metric": metric,
                "Player 1": round(p1_val, 3),
                "Player 2": round(p2_val, 3),
                "Better":   winner,
            })
        df_h2h = pd.DataFrame(rows)
        st.dataframe(
            df_h2h.style.applymap(
                lambda v: f"color: {THEME['green']}; font-weight: bold"
                if v == "P1" else (
                    f"color: {THEME['orange']}; font-weight: bold"
                    if v == "P2" else ""
                ),
                subset=["Better"]
            ),
            use_container_width=True, hide_index=True,
        )


# ─────────────────────────────────────────────────────────────────────────────
# ⑨ COACHING INSIGHTS — AI-generated from data
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Coaching Insights</div>",
            unsafe_allow_html=True)

def gen_insights(df_shots, df_bio, pid=None):
    label = f"Player {pid}" if pid else "All Players"
    insights = []

    if df_shots.empty:
        return insights

    # 1. Overall quality
    good_r = (df_shots["quality"]=="GOOD").mean()
    bad_r  = (df_shots["quality"]=="BAD").mean()
    if good_r > 0.6:
        insights.append(("good",  f"✅ {label}: Excellent overall — {good_r*100:.0f}% shots rated GOOD"))
    elif bad_r > 0.4:
        insights.append(("bad",   f"🔴 {label}: {bad_r*100:.0f}% shots rated BAD — technique needs work"))
    else:
        insights.append(("warn",  f"🟡 {label}: Consistent mid-level play — {good_r*100:.0f}% GOOD"))

    # 2. Weakest shot type
    shot_quality = df_shots.groupby("shot_type")["quality_score"].mean()
    if not shot_quality.empty:
        weakest = shot_quality.idxmin()
        weak_val = shot_quality.min()
        insights.append(("bad" if weak_val < 0.4 else "warn",
            f"⚠️ Weakest shot: **{weakest}** (avg quality score {weak_val:.2f}/1.0) — prioritise in training"))

    # 3. Best shot type
    best = shot_quality.idxmax()
    best_val = shot_quality.max()
    insights.append(("good",
        f"💪 Strongest shot: **{best}** (avg quality score {best_val:.2f}/1.0) — use this as go-to weapon"))

    # 4. Jump smash check
    smash = df_shots[df_shots["shot_type"]=="SMASH"]
    if not smash.empty:
        jump_smash_r = smash["jump_at_contact"].mean()
        if jump_smash_r < 0.3:
            insights.append(("bad",
                f"🦘 Only {jump_smash_r*100:.0f}% smashes were jump smashes — work on jump technique for more power"))
        else:
            insights.append(("good",
                f"🦘 {jump_smash_r*100:.0f}% smashes are jump smashes — great aerial game"))

    # 5. Elbow extension
    if "elbow_extension_norm" in df_shots.columns:
        avg_elbow = df_shots["elbow_extension_norm"].mean()
        if avg_elbow < 0.7:
            insights.append(("warn",
                f"💪 Avg elbow extension: {avg_elbow*100:.0f}% — extend arm fully at contact for more power"))

    # 6. Recovery
    avg_rec = df_shots["recovery_score"].mean()
    if avg_rec < 0.5:
        insights.append(("bad",
            f"🏃 Recovery score: {avg_rec:.2f} — returning to court centre after shots needs improvement"))
    else:
        insights.append(("good",
            f"🏃 Good court recovery score: {avg_rec:.2f} — returning well after shots"))

    # 7. Reaction time
    avg_react = df_shots["reaction_time_s"].mean()
    if avg_react > 4.0:
        insights.append(("warn",
            f"⏱️ Avg reaction time: {avg_react:.1f}s — work on transitioning between shots faster"))
    else:
        insights.append(("good",
            f"⏱️ Quick reactions: {avg_react:.1f}s avg between shots — excellent tempo"))

    # 8. Shuttle speed
    avg_spd = df_shots["shuttle_speed_kmh"].mean()
    if avg_spd < 60:
        insights.append(("warn",
            f"🏸 Avg shuttle speed: {avg_spd:.0f} km/h — work on generating more pace"))
    elif avg_spd > 85:
        insights.append(("good",
            f"🏸 High average speed: {avg_spd:.0f} km/h — powerful hitter"))

    # 9. Contact height for smash
    if not smash.empty:
        avg_contact = smash["contact_height_norm"].mean()
        if avg_contact < 0.5:
            insights.append(("bad",
                f"📍 Smash contact too low (avg {avg_contact:.2f}) — meet shuttle higher to increase angle"))

    # 10. Net shot quality
    netshot = df_shots[df_shots["shot_type"]=="NETSHOT"]
    if not netshot.empty:
        net_good = (netshot["quality"]=="GOOD").mean()
        if net_good < 0.4:
            insights.append(("bad",
                f"🕸️ Net play needs work — only {net_good*100:.0f}% NETSHOTS rated GOOD"))

    return insights

col1, col2 = st.columns(2)
card_tmpl = '<div class="insight-card {cls}"><span style="font-size:13px">{text}</span></div>'

for col_idx, pid in enumerate(list(players) + ([] if len(players) > 1 else [None])):
    df_p_shots = shots[shots["player_id"]==pid] if pid else shots
    df_p_bio   = bio[bio["player_id"]==pid]     if pid else bio
    ins = gen_insights(df_p_shots, df_p_bio, pid)

    with (col1 if col_idx % 2 == 0 else col2):
        label = f"#### Player {pid} Insights" if pid else "#### Overall Insights"
        st.markdown(label)
        for cls, text in ins:
            st.markdown(
                card_tmpl.format(cls=cls, text=text),
                unsafe_allow_html=True
            )


# ─────────────────────────────────────────────────────────────────────────────
# ⑩ SHOT DETAIL TABLE
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("<div class='section-header'>Shot Events — Detailed Table</div>",
            unsafe_allow_html=True)

display_cols = [
    "frame","player_id","shot_type","quality","quality_score",
    "shuttle_speed_kmh","reaction_time_s","contact_height_norm",
    "wrist_above_nose","jump_at_contact","elbow_straight",
    "recovery_score","quality_reason","coaching_tip",
]
display_cols = [c for c in display_cols if c in shots.columns]

shots_display = shots[display_cols].sort_values("frame")

def color_quality(val):
    if val == "GOOD":    return f"color: {THEME['green']}; font-weight:bold"
    if val == "AVERAGE": return f"color: {THEME['yellow']}"
    if val == "BAD":     return f"color: {THEME['red']}"
    return ""

def color_shot(val):
    c = SHOT_COLORS.get(val, THEME["muted"])
    return f"color: {c}; font-weight: bold"

shot_filter = st.multiselect(
    "Filter by shot type", options=list(SHOT_COLORS.keys()),
    default=list(SHOT_COLORS.keys()))
qual_filter = st.multiselect(
    "Filter by quality", options=["GOOD","AVERAGE","BAD"],
    default=["GOOD","AVERAGE","BAD"])

filtered = shots_display[
    shots_display["shot_type"].isin(shot_filter) &
    shots_display["quality"].isin(qual_filter)
] if shot_filter and qual_filter else shots_display

st.dataframe(
    filtered.style
    .applymap(color_quality, subset=["quality"])
    .applymap(color_shot,    subset=["shot_type"])
    .format({
        "quality_score":      "{:.2f}",
        "shuttle_speed_kmh":  "{:.1f} km/h",
        "reaction_time_s":    "{:.2f}s",
        "contact_height_norm":"{:.3f}",
        "recovery_score":     "{:.3f}",
    }, na_rep="—"),
    use_container_width=True,
    height=350,
)

st.caption(
    f"Showing {len(filtered)} of {len(shots)} shot events  ·  "
    f"Generated by PlaySight AI"
)